@startuml

package facade {

    Interface PresentationServices
    Abstract Class Presentation
    PresentationServices : startPresentation()
    PresentationServices : stopPresentation()
    PresentationServices : nextSlide()
    PresentationServices : previousSlide()
    Presentation .up.|> PresentationServices
    SimplePresentation -up-|> Presentation
}


package bridge {

    package style {
        Interface Style
        Level1 -up-|> Style
        Level2 -up-|> Style
        Level3 -up-|> Style
        Level4 -up-|> Style

    }

    package composite {

        Abstract Class Item

        Text .up.|> Item
        Figure .up.|> Item
        Table .up.|> Item
        Composite .up.|> Item
        Composite -up-> "*" Item

        Item -right-> Style

    }

}

package iterator {

    Interface SlideShow
    Interface Iterator

    SlideShowImpl .up.|> SlideShow
    SlideIterator -up-|> Iterator
    Slide -down-> "*" Item
    SlideShowImpl -down-> SlideList
    SlideShowImpl -left-> Iterator
    SlideList -left-> SlideIterator
    SlideList --> "*" Slide

    SlideShow : next()
    SlideShow : hasNext()
    SlideShow : next()
    SlideShow : hasPrevious()

    SlideList : getIterator()

    Slide -left-> "0..1" Transition : next
    Slide -left-> "0..1" Transition : previous

}

package strategy {

    Interface PresentationStartRule
    PresentationStartRule : canStart()
    Presentation -right-> PresentationStartRule
    PresentationStartRuleImpl .up.|> PresentationStartRule

    Interface PresentationStopRule
    PresentationStopRule : canStop()
    Presentation -right-> PresentationStopRule
    PresentationStopRuleImpl .up.|> PresentationStopRule

    Interface NextSlideRule
    NextSlideRule : canNavigate()
    SlideShowImpl -right-> NextSlideRule
    NextSlideRuleImpl .up.|> NextSlideRule

    Interface PreviousSlideRule
    PreviousSlideRule : canNavigate()
    SlideShowImpl -right-> PreviousSlideRule
    PreviousSlideRuleImpl .up.|> PreviousSlideRule


}


SimplePresentation --> SlideShow

@enduml
